### ISSUE TITLE
Metrics format changed?

### ISSUE THREAD

**Issue by razius** [GoogleCloudPlatform/spark-on-k8s-operator#381]
I was trying to setup Prometheus metrics exporting but I couldn't make it work with the current config, it seems that the separator between the namespace and app name could have changed? 

Eg. I removed all the rules from the config (by default anything that doesn't match gets dropped) and I could see metrics again but I got the following help text:

```
# HELP spark_streaming_driver_receivers Attribute exposed for management (metrics<name=spark-popular-products.driver.popular-products.StreamingMetrics.streaming.receivers><>Value)
```
Where `spark` is the namespace and `popular-products` is the app name.

Checking the [match pattern](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/6d495e84d55d5226b3c28c51fe138a3d123d8ebb/spark-docker/conf/prometheus.yaml#L23) I could see that it has a `/` as the separator. I added the rules back and I changed the match pattern to the following and it seems to work again:

```
  - pattern: metrics<name=(\w+)-(\S+)\.driver\.(\S+)\.StreamingMetrics\.streaming\.(\S+)><>Value
```

**Comment by oliver-tarrant-tessella** [comment]
I was having the same issue and changing the separator also seems to have worked for me. It doesn't feel like an ideal solution though as a `-` is allowed in the definitions in an application's yaml file which can cause mismatches in arguments. However, as a fix for now I have found changing each match pattern in the config file to start with `metrics<name=(\S+)-(\S+)` allows the metrics to be exported to prometheus again.

**Comment by liyinan926** [comment]
Do you have `"spark.metrics.namespace": "<namespace>/<name>"` in your `SparkApplication` spec?

**Comment by razius** [comment]
No, it's not filled in.

**Comment by liyinan926** [comment]
OK, can you try adding the following and see if the patterns with a `/` work?

```
spec:
    sparkConf:
        "spark.metrics.namespace": "<your app namespace>/<your app name>"
```

**Comment by oliver-tarrant-tessella** [comment]
I'm afraid that adding `"spark.metrics.namespace": "<my apps namespace>/<my apps name>"` to my spark application's spec has made no difference for me when using the `/` separator.

**Comment by razius** [comment]
Can confirm, nothing changed.

**Comment by liyinan926** [comment]
OK, so looks like `/` is not a valid separator. We will fix the patterns.

**Comment by yuchaoran2011** [comment]
This issue can be closed. As an FYI, the bug was introduced in this [commit](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/32a48e89644b1a85091ee7196f14b9ff7d574dd1#diff-bd3f415095b61c38aed8f3276035fbf3), where the separator changed from a backslash to a hyphen.

**Comment by razius** [comment]
I see config was fixed in ba9258d84355ba21598206e4448b544ee1a30d6b as well.

**Comment by liyinan926** [comment]
Fixed in #405.

**Comment by oliver-tarrant-tessella** [comment]
I updated my spark operator a few days ago and I am having issues getting metrics again. I see the matching pattern has changed again and I have updated the all files to the latest versions but I still can't get metrics from the driver and executor pods. The fix from #405 did work but I think it may have broken again somewhere in  #409 or #421
